<?php

namespace tool_copy_courses\task;

use core\task\asynchronous_copy_task;

class copy_course_task extends asynchronous_copy_task
{
    public function execute()
    {
        global $DB;

        parent::execute(); // TODO: Change the autogenerated stub

        $course = $DB->get_record('course', array('id' => $this->get_custom_data()->new_courseid));

        $course->shortname = $this->get_custom_data()->shortname;
        $course->fullname = $this->get_custom_data()->fullname;

        $DB->update_record('course', $course);
        mtrace("Coursed updated...");
    }

}