<?php
/**
 * Plugin version and other meta-data are defined here.
 *
 * @package     tool_copy_courses
 * @copyright   2023 Jhon Rangel <jrangelardila@gmail.com>
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */


namespace tool_copy_courses\task;

require_once($CFG->dirroot . '/backup/util/includes/backup_includes.php');
require_once($CFG->dirroot . '/backup/util/includes/restore_includes.php');

use core\task\asynchronous_copy_task;

class copy_course_task extends asynchronous_copy_task
{
    public function execute()
    {
        global $DB;

        parent::execute(); // TODO: Change the autogenerated stub

        $course = $DB->get_record('course', array('id' => $this->get_custom_data()->new_courseid));

        $course->shortname = $this->get_custom_data()->shortname;
        $course->fullname = $this->get_custom_data()->fullname;

        $DB->update_record('course', $course);
        mtrace("Coursed updated...");
    }

}